---
version: 2

test: &test
  docker:
    - image: library/rust:1.20-jessie
  working_directory: /tmp/build
  steps:
    - setup_remote_docker:
        version: 17.06.0-ce
        reusable: true
    - run:
        name: Test Docker
        command: docker info
    - checkout
    - run:
        name: Test
        command: |
          cargo test

defaults: &defaults
  docker:
    - image: library/docker:17.06.0-ce
  working_directory: /tmp/build
  environment:
    - BINARY=resin-wifi-connect
    - BUILD_OS=linux
  steps:
    - setup_remote_docker:
        version: 17.06.0-ce
        reusable: true
    - run:
        name: Test Docker
        command: docker info
    - checkout
    - run:
        name: Run build
        command: |
          set -x
          pwd
          ls -lah
          ci/build.sh
    - run:
        name: Prepare for deploy
        command: |
          apk add --no-cache git
          TRAVIS_TAG=$(git describe --tags) || true

          mkdir -p $TRAVIS_TAG/dist
          sudo mv target/$TARGET/release/$BINARY $TRAVIS_TAG/dist/$BINARY
          cp -R public $TRAVIS_TAG/dist/public
          tar -czvf $TRAVIS_TAG/$BINARY-$TRAVIS_TAG-$BUILD_OS-$ARCH.tar.gz -C $TRAVIS_TAG/dist .
          rm -rdf $TRAVIS_TAG/dist

jobs:
  aarch64:
    <<: *defaults
    environment:
      ARCH: aarch64
      TARGET: aarch64-unknown-linux-gnu
  armv7hf:
    <<: *defaults
    environment:
      ARCH: armv7hf
      TARGET: armv7-unknown-linux-gnueabihf
  rpi:
    <<: *defaults
    environment:
      ARCH: rpi
      TARGET: arm-unknown-linux-gnueabihf
  i386:
    <<: *defaults
    environment:
      ARCH: i386
      TARGET: i686-unknown-linux-gnu
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
      TARGET: x86_64-unknown-linux-gnu
  test:
    <<: *test

workflows:
  version: 2
  test:
    jobs:
      - test
  build:
    jobs:
      - aarch64
      - armv7hf
      - rpi
      - i386
      - amd64

